// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rounddecimalofmoneyowedto2decimalplaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rounddecimalofmoneyowedto2decimalplaces));
        
        string IMigrationMetadata.Id
        {
            get { return "201705051538569_round decimal of moneyowed to 2 decimal places"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
