// <auto-generated />
namespace TrashPickup.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcustomerslisttoemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcustomerslisttoemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021504342_added customers list to employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
